### ISSUE TITLE
个人认为imagetools的图片操作功能也能迁移进来

### ISSUE THREAD

**Issue by jcjrobert** [MeetWq/meme-generator#1]
不和memes放在一起，单独加个imagetools放置即可

**Comment by MeetWq** [comment]
我觉得 imagetools 和这个库的定位不符，而且 imagetools 都是一些简单的图片操作，应该有很多类似的工具或网站了，目前 imagetools 主要目的还是方便在 qq 里做一些操作

**Comment by MeetWq** [comment]
而且要加的话感觉另建仓库比较合适，而不是硬套表情的这一套逻辑
