### ISSUE TITLE
请求添加表情

### ISSUE THREAD

**Issue by yhzcake** [MeetWq/meme-generator#100]
昨天闲来无事做了一套逆转裁判气泡的表情,想来可以塞在这里面,但是我不太会写,所以看看有没有人愿意适配一下
需求:字符1-5,图片0;
字体[庞门正道粗书体.zip](https://github.com/MeetWq/meme-generator/files/15184573/default.zip)
表情psd文件[逆转裁判.zip](https://github.com/MeetWq/meme-generator/files/15184581/default.zip)

**Comment by yhzcake** [comment]
背景气泡或许也可以作为可选输入项

**Comment by MeetWq** [comment]
大致写了一下，可以试一下 #101

**Comment by MeetWq** [comment]
字体要手动安装，装完删一下 matplotlib 缓存

**Comment by yhzcake** [comment]
> 字体要手动安装，装完删一下 matplotlib 缓存

我做psd的时候肯定装字体了,不过matplotlib 缓存怎么清?

**Comment by MeetWq** [comment]
https://github.com/MeetWq/meme-generator/blob/main/docs/install.md#%E5%AD%97%E4%BD%93%E5%AE%89%E8%A3%85

**Comment by yhzcake** [comment]
> https://github.com/MeetWq/meme-generator/blob/main/docs/install.md#%E5%AD%97%E4%BD%93%E5%AE%89%E8%A3%85

还是不行,不过我是通过nonebot那边用的,我去那边发issue吧
