### ISSUE TITLE
逆转裁判气泡 这个meme的字体错误

### ISSUE THREAD

**Issue by ElaineOwO** [MeetWq/meme-generator#107]
RT 也已经把包里的字体全都丢进C:\Windows\Fonts了  但生成的图片还是字体不对 
![0bed18cd495b449826a6398df392dc1a_720](https://github.com/MeetWq/meme-generator/assets/126962415/92864e22-1c15-476e-9cbf-13a7ce587021)

**Comment by MeetWq** [comment]
加新字体之后要清缓存 https://github.com/MeetWq/meme-generator/wiki/%E6%9C%AC%E5%9C%B0%E5%AE%89%E8%A3%85#%E5%AD%97%E4%BD%93%E5%AE%89%E8%A3%85
