### ISSUE TITLE
windows运行报错Logger.opt() got an unexpected keyword argument 'colors'

### ISSUE THREAD

**Issue by DuanxxPlus** [MeetWq/meme-generator#114]
![6938f920a6765e2aca3e1202118f5e0a](https://github.com/user-attachments/assets/f9dfc6df-7a35-4f05-ab94-ed952951cd20)

**Comment by MeetWq** [comment]
感觉是你的 `loguru` 版本太老了，更新一下试试

另外，建议用 pip 或 docker 安装，而不是直接运行源代码
