### ISSUE TITLE
API配置问题

### ISSUE THREAD

**Issue by fan4w** [MeetWq/meme-generator#12]
![image](https://user-images.githubusercontent.com/127591077/227486273-173dc6fe-3dae-401f-af20-dabc1e10e537.png)
请问 `meme run`之后出现这种情况应该怎么办

**Comment by MeetWq** [comment]
多了个 `/` 吧

**Comment by fan4w** [comment]
> 多了个 `/` 吧

已经解决，谢谢大佬
