### ISSUE TITLE
+1表情期望

### ISSUE THREAD

**Issue by yhzcake** [MeetWq/meme-generator#122]
[+1.zip](https://github.com/user-attachments/files/16539984/%2B1.zip)
分辨率低的原因是+1的图标是截图的..
老鼠原图是这个
![image](https://github.com/user-attachments/assets/4f75c4f4-5108-4263-9d29-ef72978e4782)

**Comment by dkqdb66** [comment]
![EE479CBAC8B119AD02C093FDCAF05484](https://github.com/user-attachments/assets/7fd4df51-589f-42a2-a67f-d574e2ae34dc)
好快

**Comment by yhzcake** [comment]
孩子很满意,大佬好快的摸
