### ISSUE TITLE
高低情商high_EQ报错

### ISSUE THREAD

**Issue by DuanxxPlus** [MeetWq/meme-generator#131]
![8f4cfc60a583034aa7639e6007d6002c](https://github.com/user-attachments/assets/9e5704f5-d696-400f-b34a-26803a24bb0f)
![32ff6160a7f3cf2cb86181af013e05e6](https://github.com/user-attachments/assets/c41953c2-d7db-48f1-bbd2-c2ace27a275c)
在swagger上试，high_EQ报错，images空值，texts传两个，args传空值和默认都试了，报错，不知道是我操作不对还是有bug，其他试了几个没问题

**Comment by MeetWq** [comment]
这个网页填多段文字时生成的指令有问题，正常应该是：
```
  -F 'texts=高情商' \
  -F 'texts=低情商' \
```
这样

你可以试试别的需要多段文字的表情，应该都是这样
