### ISSUE TITLE
字符画生成有些异常

### ISSUE THREAD

**Issue by GOOD-AN** [MeetWq/meme-generator#14]
例1:
发送
![image](https://user-images.githubusercontent.com/53306377/227782712-cc90cc26-8412-4679-a716-4067318c2339.png)
返回
![image](https://user-images.githubusercontent.com/53306377/227782731-bcd94441-d9e6-4d28-96c4-4cc1221ba49b.png)
例2:
发送
![image](https://user-images.githubusercontent.com/53306377/227782963-72389e6d-3fda-457e-a168-0642142a0909.png)
返回
![image](https://user-images.githubusercontent.com/53306377/227782989-78b1c64e-ada9-4b82-bbea-e4a876839c30.png)

**Comment by MeetWq** [comment]
字符画需要用特定的字体，请按照readme中的说明检查字体是否安装正确

**Comment by GOOD-AN** [comment]
是的，字体安装了，命令检测也是有的，但是运行就会报错`findfont: Font family ['Consolas'] not found. Falling back to DejaVu Sans.`

**Comment by MeetWq** [comment]
![Snipaste_2023-03-27_14-33-58](https://user-images.githubusercontent.com/33149974/227859490-015d9662-a847-427f-b754-e487c5bc02d8.png)
你看一下 matplotlib 的字体缓存文件里面有没有 Consolas，没有的话删掉重新运行再试

**Comment by GOOD-AN** [comment]
确实是这个问题，非常感谢！！！
