### ISSUE TITLE
meme download报错

### ISSUE THREAD

**Issue by YipSzeho** [MeetWq/meme-generator#143]
ubuntu 22.04，通过pip安装generator后尝试下载表情时报错。
`yipszeho@ubuntu:~$ meme download
08-17 12:27:29 [INFO] meme_generator.log | Config file path: /home/yipszeho/.config/meme_generator/config.toml
Traceback (most recent call last):
  File "/home/yipszeho/.local/bin/meme", line 8, in <module>
    sys.exit(main())
  File "/home/yipszeho/.local/lib/python3.10/site-packages/meme_generator/cli.py",
line 222, in main
    url = sub_result.options["url"].args["url"]
KeyError: 'url'`

**Comment by MeetWq** [comment]
这是 `arclet-alconna` 的 bug，可以暂时降级：
```
pip install arclet-alconna=="1.8.26"
```
或者等它更新

**Comment by MeetWq** [comment]
`arclet-alconna` 已更新，更新 `arclet-alconna` 就能解决
