### ISSUE TITLE
表情顶尖和顶是不是冲突了？

### ISSUE THREAD

**Issue by wzwei1990** [MeetWq/meme-generator#149]
表情顶尖发送不了

**Comment by MeetWq** [comment]
没有冲突，你确认一下参数数量是否正确

**Comment by wzwei1990** [comment]
用的机器人[ikechan8370/yunzai-meme](https://github.com/ikechan8370/yunzai-meme) 接入的

**Comment by MeetWq** [comment]
那是 yunzai-meme 的问题，具体怎么处理关键词与 meme-generator 无关
