### ISSUE TITLE
请问使用pip安装如何更新新增表情

### ISSUE THREAD

**Issue by Nahida-77** [MeetWq/meme-generator#155]
请问使用pip安装如何更新新增表情
使用
pip install -U meme_generator显示

Looking in indexes: http://mirrors.aliyun.com/pypi/simple/
Requirement already satisfied: meme_generator in c:\users\32582\appdata\local\programs\python\python38-32\lib\site-packages (0.0.19.1)
Requirement already satisfied: dateparser<2.0.0,>=1.2.0 in c:\users\32582\appdata\local\programs\python\python38-32\lib\site-packages (from meme_generator) (1.2.0)
Requirement already satisfied: fastapi<1.0.0,>=0.93.0 in c:\users\32582\appdata\local\programs\python\python38-32\lib\site-packages (from meme_generator) (0.112.0)
Requirement already satisfied: filetype<2.0.0,>=1.2.0 in c:\users\32582\appdata\local\programs\python\python38-32\lib\site-packages (from meme_generator) (1.2.0)
等

使用
meme download显示

08-29 21:25:30 [INFO] meme_generator.log | Config file path: C:\Users\32582\AppData\Roaming\meme_generator\config.toml
08-29 21:25:31 [WARNING] meme_generator.download | No resource url available.

**Comment by MeetWq** [comment]
0.0.20 及以上版本不再支持 python 3.8 了，你需升级 python 版本
