### ISSUE TITLE
【建议】可以把文字表情包和图像表情包区分开嘛

### ISSUE THREAD

**Issue by ElaineOwO** [MeetWq/meme-generator#16]
RT 这样混在一起感觉有一丢丢乱。。希望可以用什么标识或排序区分

**Comment by jcjrobert** [comment]
讲道理，表情一多都会觉得乱，无论你分不分（）

**Comment by ElaineOwO** [comment]
> 讲道理，表情一多都会觉得乱，无论你分不分（） 如果是和网页端对接可以用图片辅助显示，那还好 但是QQ机器人就不太好说，因为表情太多了，直接加预览图片反而不好显示 虽然有表情详细可以看，但有时候会看花（x）

比如在图片表情后面标注（图） 在文字表情后面标注（文）

**Comment by MeetWq** [comment]
> 比如在图片表情后面标注（图） 在文字表情后面标注（文）

目前不太想严格区分”图片“和”文字“表情
如果把 需要图片数>=1 的表情定义为”图片表情“，总感觉怪怪的
而且之后可能会有图片和文字输入都能处理的表情

**Comment by ElaineOwO** [comment]
> > 比如在图片表情后面标注（图） 在文字表情后面标注（文）
> 
> 目前不太想严格区分”图片“和”文字“表情 如果把 需要图片数>=1 的表情定义为”图片表情“，总感觉怪怪的 而且之后可能会有图片和文字输入都能处理的表情

酱紫 那就按作者的意思来吧

**Comment by AshenAshes** [comment]
赞同，现在都是用#表情包制作 命令来看的，但是没有区分后面跟文字还是图片，就导致多了一步#表情详情 表情名 去看具体使用方法。希望#表情包制作 命令可以把文和图分成两列（不过有些文图都要的就更麻烦了）。或者就每一类开头写个 表情名 文字1 文字2 图片1，类似这样的说明来辨别？

**Comment by ElaineOwO** [comment]
感觉可以重新排版一下 把需要图片的放在一起 需要文字的放在一起 两者都需要的放在一起 这样更直观一些

**Comment by MeetWq** [comment]
新版增加了图片和文字的图标，可以试试。有别的想法可以再提
