### ISSUE TITLE
去除返回文本

### ISSUE THREAD

**Issue by xinanke** [MeetWq/meme-generator#164]
某些需要文本合成的表情包，当文本过长时会提示文本某某过长，能否只提示文本过长而不是返回全部的文本

**Comment by MeetWq** [comment]
有什么理由吗

**Comment by xinanke** [comment]
> 有什么理由吗

有些用户会发违规长内容，机器人返回直接被警告

**Comment by xinanke** [comment]
> 有什么理由吗

我修改了meme_generator/exception.py的第31行代码，删除了"self.txt"，重新运行，仍然会返回文本，所以来这里问😭

**Comment by xinanke** [comment]
> > 有什么理由吗
> 
> 我修改了meme_generator/exception.py的第31行代码，删除了"self.text"，重新运行，仍然会返回文本，所以来这里问😭

**Comment by MeetWq** [comment]
e1e6090
