### ISSUE TITLE
关于使用PHP调用API时发生图片找不到的错误

### ISSUE THREAD

**Issue by why0209** [MeetWq/meme-generator#18]
<?php

$cfile = curl_file_create('1.jpg','image/jpeg','test_name');
header('Content-Type: image/jpeg');
echo post("http://127.0.0.1:2233/memes/sit_still/",array(
    'images' => array(
        $cfile
        ),
    'texts' => array(
        '测试'
        ),
));

function post($url,$postdata)
{
    $ch = curl_init();
    curl_setopt($ch, CURLOPT_POST, 1);
    curl_setopt($ch, CURLOPT_URL, $url);
    curl_setopt($ch, CURLOPT_POSTFIELDS, $postdata);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_HTTPHEADER, array(
            'Content-Type: multipart/form-data',
            'Accept: application/json',
        )
   	);
    $response = curl_exec($ch);
    curl_close($ch);
    return $response;
}

这是一段PHP代码 大佬我该如何定义待生成图片的编码或路径？
现在这段代码报 {"detail":[{"loc":["body","images",0],"msg":"Expected UploadFile, received: ","type":"value_error"}]}
提示图片文件未找到 我也尝试将$cfile参数转换为base64、二进制、绝对路径等，依旧提示这个错误。

**Comment by MeetWq** [comment]
php 我不懂哦

[docs/examples/test_api.py](https://github.com/MeetWq/meme-generator/blob/main/docs/examples/test_api.py) 这是 python 的请求示例

下面是 fastapi docs 页面生成的 curl 的请求示例
![image](https://user-images.githubusercontent.com/33149974/228551967-c7a90dcc-ff0b-4862-8829-7a92afd42ff6.png)

**Comment by why0209** [comment]
大佬 我使用fastapi生成图片或文字不为1时的表情包 发生了文字找不到的问题 这个标准的请求应该是怎样的呢？
![image](https://user-images.githubusercontent.com/101301760/228820121-2d8f1a04-99f6-4f1b-899a-ce5e8e7f48ae.png)

**Comment by MeetWq** [comment]
这是 fastapi 生成的页面的问题

多个图片是正常的
```shell
curl -X 'POST' \
  'http://127.0.0.1:2233/memes/kiss/' \
  -H 'accept: application/json' \
  -H 'Content-Type: multipart/form-data' \
  -F 'images=@test.jpg;type=image/jpeg' \
  -F 'images=@test.jpg;type=image/jpeg' \
  -F 'args={"user_infos": []}'
```

多个文字正常调用方式如下：
```shell
curl -X 'POST' \
  'http://127.0.0.1:2233/memes/find_chips/' \
  -H 'accept: application/json' \
  -H 'Content-Type: multipart/form-data' \
  -F 'texts=我们要飞向何方' \
  -F 'texts=我打算待会去码头整点薯条' \
  -F 'texts=我说的是归根结底，活着是为了什么' \
  -F 'texts=为了待会去码头整点薯条' \
  -F 'args={"user_infos": []}'
```

**Comment by why0209** [comment]
谢谢大佬！

**Comment by why0209** [comment]
谢谢大佬！

**Comment by MaoSource** [comment]
> 这是 fastapi 生成的页面的问题
> 
> 多个图片是正常的
> 
> ```shell
> curl -X 'POST' \
>   'http://127.0.0.1:2233/memes/kiss/' \
>   -H 'accept: application/json' \
>   -H 'Content-Type: multipart/form-data' \
>   -F 'images=@test.jpg;type=image/jpeg' \
>   -F 'images=@test.jpg;type=image/jpeg' \
>   -F 'args={"user_infos": []}'
> ```
> 
> 多个文字正常调用方式如下：
> 
> ```shell
> curl -X 'POST' \
>   'http://127.0.0.1:2233/memes/find_chips/' \
>   -H 'accept: application/json' \
>   -H 'Content-Type: multipart/form-data' \
>   -F 'texts=我们要飞向何方' \
>   -F 'texts=我打算待会去码头整点薯条' \
>   -F 'texts=我说的是归根结底，活着是为了什么' \
>   -F 'texts=为了待会去码头整点薯条' \
>   -F 'args={"user_infos": []}'
> ```



> 这是fastapi生成的页面的问题
> 
> 许多图片是正常的
> 
> ```shell
> curl -X 'POST' \
>   'http://127.0.0.1:2233/memes/kiss/' \
>   -H 'accept: application/json' \
>   -H 'Content-Type: multipart/form-data' \
>   -F 'images=@test.jpg;type=image/jpeg' \
>   -F 'images=@test.jpg;type=image/jpeg' \
>   -F 'args={"user_infos": []}'
> ```
> 
> 多个文字正调使用方式如下：
> 
> ```shell
> curl -X 'POST' \
>   'http://127.0.0.1:2233/memes/find_chips/' \
>   -H 'accept: application/json' \
>   -H 'Content-Type: multipart/form-data' \
>   -F 'texts=我们要飞向何方' \
>   -F 'texts=我打算待会去码头整点薯条' \
>   -F 'texts=我说的是归根结底，活着是为了什么' \
>   -F 'texts=为了待会去码头整点薯条' \
>   -F 'args={"user_infos": []}'
> ```

不支持url的图片么？

**Comment by MeetWq** [comment]
> 不支持url的图片么？

不支持
