### ISSUE TITLE
datafile missing

### ISSUE THREAD

**Issue by yuyula2233** [MeetWq/meme-generator#188]
0.1.7版本，手动将缺失的 icudtl.dat 文件放到Lib\site-packages 文件夹下，依旧有错误

$ meme run
11-13 20:36:30 [INFO] meme_generator.log | Config file path: C:\Users\Administrator\AppData\Roaming\meme_generator\config.toml
11-13 20:36:31 [INFO] uvicorn.server | Started server process [9508]
11-13 20:36:31 [INFO] uvicorn.lifespan.on | Waiting for application startup.
11-13 20:36:31 [INFO] uvicorn.lifespan.on | Application startup complete.
11-13 20:36:31 [INFO] uvicorn.server | Uvicorn running on http://0.0.0.0:2233 (Press CTRL+C to quit)
SkIcuLoader: datafile missing: D:\Program Files\Python310\icudtl.dat.
Segmentation fault
![3EE230F3F22538846535ACB28BE1E7F0](https://github.com/user-attachments/assets/5201b34e-efae-4f33-a216-1887938ee8c0)

**Comment by MeetWq** [comment]
安装新一点的 [Visual Studio Build Tools](https://visualstudio.microsoft.com/zh-hans/downloads/?q=build+tools)，理论上需要2017以上

**Comment by yuyula2233** [comment]
已经好了，多谢大佬的解答ヽ(✿ﾟ▽ﾟ)ノ

**Comment by WangZhiyuan626** [comment]
我安装了Microsoft Visual C++ Redistributable for Visual Studio 2022也没有解决，请问大佬还做了什么操作吗

**Comment by MeetWq** [comment]
> 我安装了Microsoft Visual C++ Redistributable for Visual Studio 2022也没有解决，请问大佬还做了什么操作吗

试试 `pip install msvc-runtime`

**Comment by MagneticLine** [comment]
> > 我安装了Microsoft Visual C++ Redistributable for Visual Studio 2022也没有解决，请问大佬还做了什么操作吗
> 
> 试试 `pip install msvc-runtime`

感谢大佬，虽然还有报错，但是不会闪退可以使用了
