### ISSUE TITLE
建议加上表情包使用次数统计

### ISSUE THREAD

**Issue by jcjrobert** [MeetWq/meme-generator#2]
每使用一次，后台就统计一次，之后通过前端访问，结果更直观

**Comment by lgc2333** [comment]
#30 欢迎提建议（

**Comment by MeetWq** [comment]
目前的想法是 `meme-generator` 作为单纯的表情包制作工具，如果后续想做网站的话应该另开仓库，实现如用户、数据库之类的功能

插件端的 `nonebot-plugin-memes` 已实现使用次数统计功能
