### ISSUE TITLE
“我朋友说”表情包问题

### ISSUE THREAD

**Issue by yoiyami96** [MeetWq/meme-generator#20]
原来的表情生成方式挺好的，我朋友xx（指定名字）说  xxxxx（一段或多段文字）  xx（qq号或图片） ，现在这个很多人（包括我😭）普遍反映不会用，例如
<a href="https://imgse.com/i/pphF7kQ"><img src="https://s1.ax1x.com/2023/04/03/pphF7kQ.md.png" alt="pphF7kQ.png" border="0" /></a>
PS：撅这个表情包也很好用，大佬考虑过加回来吗

**Comment by MeetWq** [comment]
这个我还没想好该怎样实现
目前可以暂时用 --name 指定名字
如：我朋友说 --name 张三 来份涩图 @张三

“撅”不会加回来，可以去额外表情仓库自行取用

**Comment by yoiyami96** [comment]
> 这个我还没想好该怎样实现 目前可以暂时用 --name 指定名字 如：我朋友说 --name 张三 来份涩图 @张三
> 
> “撅”不会加回来，可以去额外表情仓库自行取用

才发现需要加上@才能获取qq号的头像和昵称了，感觉这种方式在群里容易打扰到别人
