### ISSUE TITLE
制作包含文字的表情的时候会崩溃

### ISSUE THREAD

**Issue by hakureireimusama** [MeetWq/meme-generator#202]
![image](https://github.com/user-attachments/assets/61f52053-0356-420b-9b19-083d5ead156f)
按照下面这个链接里面的办法处理了（复制了文件，安装了c++2022，系统用的是sever2022系统），还是不行，处理完命令会直接闪退掉nb后台
https://github.com/MeetWq/pil-utils#%E5%B7%B2%E7%9F%A5%E9%97%AE%E9%A2%98

**Comment by hakureireimusama** [comment]
DEBUG日志是这样的，现在发送表情包制作也会崩溃

PS C:\bot\xxm> .\xxm-Bot.bat

C:\bot\xxm>nb run --reload
使用 Python: C:\bot\xxm\.venv\Scripts\python.exe
启动重载监视，当前进程 [15284].
11-24 10:38:15 [SUCCESS] nonebot | NoneBot is initializing...
11-24 10:38:15 [INFO] nonebot | Current Env: prod
11-24 10:38:15 [DEBUG] nonebot | Loaded Config: {'driver': '~fastapi+~httpx+~websockets', 'host': IPv4Address('192.168.0.254'), 'port': 10244, 'log_level': 'DEBUG', 'api_timeout': 30.0, 'superusers': {'1317645806'}, 'nickname': {'小小梦'}, 'command_start': {''}, 'command_sep': {'.'}, 'session_expire_timeout': datetime.timedelta(seconds=120), 'img_cache': 'True', 'pm_version': '1.0.0', 'pm_text': 'Hi~ o(*￣▽￣*)ブ', 'bilichat_cache_serive': 'json', 'bilichat_block': 'True', 'qweather_apikey': '1239e77e6da849b284c20eaa64a9cf31', 'ps_use_env_nick': 'False', 'secret': '', 'ps_blur_radius': 4, 'ps_ignore_no_io_disk': 'False', 'pm_username': 'Administrator', 'ps_ignore_bad_parts': 'True', 'bilichat_dynamic': 'False', 'bilichat_rss_base': 'http://192.168.0.254:1200/', 'ps_test_sites': [{'name': 'bilibili', 'url': 'https://bilibili.com'}, {'name': '百度', 'url': 'https://baidu.com'}, {'name': 'Google', 'url': 'https://google.com', 'use_proxy': True}], 'ps_ignore_nets': ['^lo$', '^Loopback'], 'ps_ignore_disk_ios': [], 'bilichat_cmd_start': '', 'pm_plugin': 2, 'ps_max_text_len': 18, 'ps_only_su': 'True', 'bilichat_browser_shot_quality': 60, 'ps_bg_color': [255, 255, 255, 150], 'qweather_apitype': 0, 'pm_password': 774084806, 'ps_custom_bg': [], 'ps_need_at': 'False', 'ps_footer_size': 22, 'ps_font': 'C:/Windows/Fonts/msjhbd.ttc', 'ps_ignore_0b_net': 'True', 'bilichat_command_to_me': 'False', 'ps_ignore_parts': [], 'ps_mask_color': [255, 255, 255, 125], 'access_token': '', 'pm_name': '小小梦帮助', 'bilichat_cd_time': 300, 'ps_test_timeout': 5, 'pm_enable_web': 'True'}
11-24 10:38:16 [DEBUG] nonebot | Succeeded to load adapter "OneBot V11"
11-24 10:38:16 [SUCCESS] nonebot | Succeeded to load plugin "echo" from "nonebot.plugins.echo"
11-24 10:38:16 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_alconna:uniseg" from "nonebot_plugin_alconna.uniseg"
11-24 10:38:16 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_alconna"
11-24 10:38:16 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_waiter"
11-24 10:38:16 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_session"
11-24 10:38:16 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_userinfo"
11-24 10:38:16 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_localstore"
11-24 10:38:17 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_orm"
11-24 10:38:17 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_session_orm"
11-24 10:38:21 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_memes"
11-24 10:38:21 [SUCCESS] nonebot | Running NoneBot...
11-24 10:38:21 [DEBUG] nonebot | Loaded adapters: OneBot V11
11-24 10:38:21 [INFO] uvicorn | Started server process [1900]
11-24 10:38:21 [INFO] uvicorn | Waiting for application startup.
11-24 10:38:21 [DEBUG] alembic | Context impl SQLiteImpl.
11-24 10:38:21 [DEBUG] alembic | Will assume non-transactional DDL.
11-24 10:38:21 [INFO] nonebot_plugin_orm | 没有检测到新的升级操作
11-24 10:38:21 [INFO] nonebot_plugin_memes | 正在检查资源文件...
11-24 10:38:21 [INFO] uvicorn | Application startup complete.
11-24 10:38:21 [INFO] uvicorn | Uvicorn running on http://192.168.0.254:10244 (Press CTRL+C to quit)
11-24 10:38:21 [INFO] uvicorn | ('192.168.0.254', 57759) - "WebSocket /onebot/v11/ws" [accepted]
11-24 10:38:21 [INFO] nonebot | OneBot V11 | Bot 1273834131 connected
11-24 10:38:21 [INFO] websockets | connection open
11-24 10:38:21 [INFO] uvicorn | ('192.168.0.254', 57760) - "WebSocket /onebot/v11/ws" [accepted]
11-24 10:38:21 [INFO] nonebot | OneBot V11 | Bot 2406306534 connected
11-24 10:38:21 [INFO] websockets | connection open
11-24 10:38:21 [INFO] uvicorn | ('192.168.0.254', 57761) - "WebSocket /onebot/v11/ws" [accepted]
11-24 10:38:21 [INFO] nonebot | OneBot V11 | Bot 3659542263 connected
11-24 10:38:21 [INFO] websockets | connection open
11-24 10:38:21 [INFO] uvicorn | ('192.168.0.254', 57762) - "WebSocket /onebot/v11/ws" [accepted]
11-24 10:38:21 [INFO] nonebot | OneBot V11 | Bot 1279993790 connected
11-24 10:38:21 [INFO] websockets | connection open
11-24 10:38:22 [SUCCESS] nonebot | OneBot V11 3659542263 | [message.group.normal]: Message 246992478 from 739113598@[群:1163168654] '你的鲈鱼太贵了'
11-24 10:38:22 [DEBUG] nonebot | Checking for matchers in priority 1...
11-24 10:38:22 [DEBUG] nonebot | Checking for matchers in priority 11...
11-24 10:38:22 [DEBUG] nonebot | Checking for matchers in priority 12...
11-24 10:38:23 [DEBUG] nonebot | Checking for matchers completed
11-24 10:38:23 [DEBUG] meme_generator | Available resource urls: ['https://fastly.jsdelivr.net/gh/MeetWq/meme-generator@', 'https://raw.gitmirror.com/MeetWq/meme-generator/', 'https://cdn.jsdelivr.net/gh/MeetWq/meme-generator@']
11-24 10:38:25 [SUCCESS] nonebot | OneBot V11 3659542263 | [message.group.normal]: Message 1500196209 from 739113598@[群:1163168654] '[image:summary=[动画表情],file=000001484e61704361744f6e65426f747c4d736746696c657c327c3131363331363...,sub_type=1,file_id=000001484e61704361744f6e65426f747c4d736746696c657c327c3131363331363...,url=https://multimedia.nt.qq.com.cn/download?appid=1407&fileid=EhTfDr4S...,file_size=25013,file_unique=3f4aa205a8325ca445cbad39e3bb1cf5]'
11-24 10:38:25 [DEBUG] nonebot | Checking for matchers in priority 1...
11-24 10:38:25 [DEBUG] nonebot | Checking for matchers in priority 11...
11-24 10:38:25 [DEBUG] nonebot | Checking for matchers in priority 12...
11-24 10:38:25 [DEBUG] nonebot | Checking for matchers completed
11-24 10:38:32 [SUCCESS] nonebot | OneBot V11 3659542263 | [message.group.normal]: Message 651038229 from 739113598@[群:1163168654] '我家里做饭吃不饱'
11-24 10:38:32 [DEBUG] nonebot | Checking for matchers in priority 1...
11-24 10:38:32 [DEBUG] nonebot | Checking for matchers in priority 11...
11-24 10:38:32 [DEBUG] nonebot | Checking for matchers in priority 12...
11-24 10:38:32 [DEBUG] nonebot | Checking for matchers completed
11-24 10:38:34 [SUCCESS] nonebot | OneBot V11 3659542263 | [message.group.normal]: Message 1201334854 from 358543249@[群:1163168654] '鲈鱼在超市20一条'
11-24 10:38:34 [DEBUG] nonebot | Checking for matchers in priority 1...
11-24 10:38:34 [DEBUG] nonebot | Checking for matchers in priority 11...
11-24 10:38:34 [DEBUG] nonebot | Checking for matchers in priority 12...
11-24 10:38:34 [DEBUG] nonebot | Checking for matchers completed
11-24 10:38:35 [SUCCESS] nonebot | OneBot V11 2406306534 | [message.group.normal]: Message 145991549 from 2839680568@[群:877270879] '加班'
11-24 10:38:35 [DEBUG] nonebot | Checking for matchers in priority 1...
11-24 10:38:35 [DEBUG] nonebot | Checking for matchers in priority 11...
11-24 10:38:35 [DEBUG] nonebot | Checking for matchers in priority 12...
11-24 10:38:35 [DEBUG] nonebot | Plugin-Alconna | Alconna::加班 对 "加班" 的解析结果是 (matched=True, header_match=(origin='加班' result='加班' matched=True groups={}), main_args={'meme_params': ()})
11-24 10:38:35 [INFO] nonebot | Event will be handled by AlconnaMatcher(type='', module=nonebot_plugin_memes.matchers.command, lineno=163)
11-24 10:38:35 [DEBUG] nonebot | Running AlconnaMatcher(type='', module=nonebot_plugin_memes.matchers.command, lineno=163)
11-24 10:38:35 [DEBUG] nonebot | Running handler Dependent(call=_)
11-24 10:38:35 [INFO] nonebot_plugin_memes | 输入图片数量不符，图片数量应为 1
11-24 10:38:35 [INFO] nonebot | AlconnaMatcher(type='', module=nonebot_plugin_memes.matchers.command, lineno=163) running complete
11-24 10:38:35 [DEBUG] nonebot | Checking for matchers completed
11-24 10:38:39 [SUCCESS] nonebot | OneBot V11 3659542263 | [message.group.normal]: Message 472155032 from 739113598@[群:1163168654] '随机拉肚子'
11-24 10:38:39 [DEBUG] nonebot | Checking for matchers in priority 1...
11-24 10:38:39 [DEBUG] nonebot | Checking for matchers in priority 11...
11-24 10:38:39 [DEBUG] nonebot | Checking for matchers in priority 12...
11-24 10:38:39 [DEBUG] nonebot | Checking for matchers completed
11-24 10:38:40 [SUCCESS] nonebot | OneBot V11 3659542263 | [message.group.normal]: Message 1769419882 from 358543249@[群:1163168654] '啊？'
11-24 10:38:40 [DEBUG] nonebot | Checking for matchers in priority 1...
11-24 10:38:40 [DEBUG] nonebot | Checking for matchers in priority 11...
11-24 10:38:40 [DEBUG] nonebot | Checking for matchers in priority 12...
11-24 10:38:41 [DEBUG] nonebot | Checking for matchers completed
11-24 10:38:42 [SUCCESS] nonebot | OneBot V11 1279993790 | [message.private.friend]: Message 971218655 from 1317645806 '表情包制作'
11-24 10:38:42 [DEBUG] nonebot | Checking for matchers in priority 1...
11-24 10:38:42 [DEBUG] nonebot | Checking for matchers in priority 11...
11-24 10:38:42 [DEBUG] nonebot | Plugin-Alconna | Alconna::表情包制作 对 "表情包制作" 的解析结果是 (matched=True, header_match=(origin='表情包制作' result='表情包制作' matched=True groups={}))
11-24 10:38:42 [INFO] nonebot | Event will be handled by AlconnaMatcher(type='', module=nonebot_plugin_memes.matchers.help, lineno=21)
11-24 10:38:42 [DEBUG] nonebot | Running AlconnaMatcher(type='', module=nonebot_plugin_memes.matchers.help, lineno=21)
11-24 10:38:42 [DEBUG] nonebot | Running handler Dependent(call=_)
停止重载监视
PS C:\bot\xxm>

**Comment by MeetWq** [comment]
试试
```
pip install msvc-runtime
```

**Comment by hakureireimusama** [comment]
> 试试
> 
> ```
> pip install msvc-runtime
> ```
还是一样的，会闪退~不过我发现别的插件也会导致这个问题，我怀疑是不是nb本身出了问题，之后我试试重装一下nb试试

**Comment by hakureireimusama** [comment]
PS C:\bot\xxm> pip install msvc-runtime
WARNING: Ignoring invalid distribution -b-cli (c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages)
Requirement already satisfied: msvc-runtime in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (14.34.31931)
WARNING: Ignoring invalid distribution -b-cli (c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -b-cli (c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages)
PS C:\bot\xxm> .\.venv\Scripts\activate
(xxm) PS C:\bot\xxm> pip install msvc-runtime
Requirement already satisfied: msvc-runtime in c:\bot\xxm\.venv\lib\site-packages (14.42.34433)
(xxm) PS C:\bot\xxm>

**Comment by hakureireimusama** [comment]
我换成了win10工作站版，全部重装了一下就好了
