### ISSUE TITLE
希望改进一下功能，回复有文字的消息生成无文字的表情包时，直接使用图片，不要识别文字

### ISSUE THREAD

**Issue by hakureireimusama** [MeetWq/meme-generator#203]
如题，会出现如下问题

11-25 11:00:44 [SUCCESS] nonebot | OneBot V11 1273834131 | [message.private.friend]: Message 951651753 from 1317645806 '[reply:id=996593247]震动'
11-25 11:00:44 [INFO] nonebot | Event will be handled by AlconnaMatcher(type='', module=nonebot_plugin_memes.matchers.command, lineno=164)
11-25 11:00:44 [INFO] nonebot_plugin_memes | 输入文字数量不符，文字数量应为 0

![image](https://github.com/user-attachments/assets/ca15b42e-0297-449c-b4a2-d67f17e6a27a)

**Comment by MeetWq** [comment]
请去 nonebot-plugin-memes 提
