### ISSUE TITLE
修改表情包触发关键字

### ISSUE THREAD

**Issue by yoiyami96** [MeetWq/meme-generator#21]
某些表情包关键字和其他插件之类冲突，例如：关注，与haruka-bot的指令相同，我想修改表情包关键字“关注”为“假装关注”，但是我在相关表情的int.py里修改keyword并没有用，请问应该如何修改

**Comment by MeetWq** [comment]
你具体是怎么改的？在 __init__.py 里改应该是可以的

**Comment by yoiyami96** [comment]
> 你具体是怎么改的？在 `__init__.py` 里改应该是可以的


<a href="https://imgse.com/i/pp57CgH"><img src="https://s1.ax1x.com/2023/04/05/pp57CgH.png" alt="pp57CgH.png" border="0" /></a>
<a href="https://imgse.com/i/pp5TxUK"><img src="https://s1.ax1x.com/2023/04/05/pp5TxUK.png" alt="pp5TxUK.png" border="0"></a>

**Comment by MeetWq** [comment]
你用的是 `nonebot_plugin_memes` 吗？`meme_generator` 地方对不对？

**Comment by yoiyami96** [comment]
> 你用的是 `nonebot_plugin_memes` 吗？`meme_generator` 地方对不对？

用的是nonebot_plugin_memes，刚刚我才发现还要把C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\meme_generator里的表情包init.py也修改了才能生效，原先我只修改了plugins\meme_generator目录下的，明明插件是从plugins目录加载的，不太明白，抱歉因为这种小问题打扰倒大佬了
<a href="https://imgse.com/i/pp5Huo6"><img src="https://s1.ax1x.com/2023/04/05/pp5Huo6.png" alt="pp5Huo6.png" border="0" /></a>

**Comment by MeetWq** [comment]
`meme_generator` 不是 nb 插件，不应该放到插件目录下，只需加载 `nonebot_plugin_memes`

**Comment by yoiyami96** [comment]
> `meme_generator` 不是 nb 插件，不应该放到插件目录下，只需加载 `nonebot_plugin_memes`

原来是我无知了，谢谢大佬解答
