### ISSUE TITLE
【建议】 表情后的图片参数能支持QQ号吗？

### ISSUE THREAD

**Issue by webjoin111** [MeetWq/meme-generator#27]
印象里之前的版本是支持这种方式的？也可能是我记错了...
好处：根据QQ号生成对应头像的表情包，这样就适用于不能或者不方便艾特某人的场景。

**Comment by jcjrobert** [comment]
1.你issue发错仓库了
2.qq前要加@
请详细看完文档再来提issue，谢谢

**Comment by MeetWq** [comment]
获取头像是插件端的事情，nonebot-plugin-memes 可以指定qq号
