### ISSUE TITLE
自建api的问题

### ISSUE THREAD

**Issue by ChthollyWn** [MeetWq/meme-generator#32]
使用docker部署的api，部署后未修改任何配置
api工具测试正常
![image](https://user-images.githubusercontent.com/85938618/236167886-09ac35b7-5bca-4a08-8d41-d7564eb2b41d.png)
对接云崽后无法正常使用
![image](https://user-images.githubusercontent.com/85938618/236168101-29cd4714-e335-419a-95d6-36ce262c97ab.png)
日志
![image](https://user-images.githubusercontent.com/85938618/236168329-860e440e-a76e-45bd-b843-db48d3e0a059.png)
看起来像是没有找到图片的路径，但是我不清楚该如何修改或者配置，请问该如何解决

**Comment by MeetWq** [comment]
"看看你的" 不在主仓库中，你需要自行添加
参考 [docker加载额外表情的方式](https://github.com/MeetWq/meme-generator/blob/main/docs/docker.md#加载额外表情)

**Comment by ChthollyWn** [comment]
> "看看你的" 不在主仓库中，你需要自行添加 参考 [docker加载额外表情的方式](https://github.com/MeetWq/meme-generator/blob/main/docs/docker.md#%E5%8A%A0%E8%BD%BD%E9%A2%9D%E5%A4%96%E8%A1%A8%E6%83%85)
![image](https://user-images.githubusercontent.com/85938618/236175926-154ff3ff-5ec9-45d6-b3d4-5fcaf7bf7e4e.png)
![image](https://user-images.githubusercontent.com/85938618/236175998-490e033a-1f70-4cbb-af15-c6155c4efedd.png)
使用 meme列表 命令时图片格式无法识别

**Comment by ChthollyWn** [comment]
![image](https://user-images.githubusercontent.com/85938618/236176513-ef057d74-3a13-4b89-a0f9-d6fb5a1ec7a8.png)
喜报这种在主仓库的表情也无法发出

**Comment by MeetWq** [comment]
那就是云崽对接的问题了

**Comment by ChthollyWn** [comment]
> 那就是云崽对接的问题了

使用默认的api是没有问题的

**Comment by MeetWq** [comment]
默认api是什么？我不太清楚云崽是用的什么

**Comment by ChthollyWn** [comment]
> 默认api是什么？我不太清楚云崽是用的什么

默认api是https://memes.ikechan8370.com
项目地址https://github.com/ikechan8370/yunzai-meme

**Comment by MeetWq** [comment]
我怀疑是你链接没写对，检查一下有没有多打斜杠之类的
