### ISSUE TITLE
希望能把5000choyen表情的emoji和文字区分开

### ISSUE THREAD

**Issue by yi03** [MeetWq/meme-generator#44]
现在5000choyen表情没有把emoji和文字区分开，如果输入文本带emoji的话大概是这种效果，看起来很怪：
![image](https://github.com/MeetWq/meme-generator/assets/32034998/80436465-49a3-47b8-8746-fd7ee44c0f89)
希望能达到类似这样的效果：
![136510328e3f849e004ed12fb84c9e3d](https://github.com/MeetWq/meme-generator/assets/32034998/ef2b9b0b-e2dd-4724-af57-0cedf66a34ab)
谢谢大佬！

**Comment by MeetWq** [comment]
新版已经没有这个问题了
