### ISSUE TITLE
在服务器上部署，server改成了0.0.0.0，但是出现如下问题怎么搞？

### ISSUE THREAD

**Issue by howardgriffin** [MeetWq/meme-generator#55]
08-28 15:40:59 [INFO] meme_generator.log | Config file path: /root/.config/meme_generator/config.toml
08-28 15:41:00 [INFO] uvicorn.server | Started server process [15502]
08-28 15:41:00 [INFO] uvicorn.lifespan.on | Waiting for application startup.
08-28 15:41:00 [INFO] uvicorn.lifespan.on | Application startup complete.
08-28 15:41:00 [INFO] uvicorn.server | Uvicorn running on http://0.0.0.0:8888 (Press CTRL+C to quit)
08-28 15:41:02 [INFO] uvicorn.protocols.http.h11_impl | 10.197.56.135:45833 - "GET / HTTP/1.1" 404
08-28 15:41:04 [INFO] uvicorn.protocols.http.h11_impl | 10.197.56.135:51240 - "GET /favicon.ico HTTP/1.1" 404

**Comment by MeetWq** [comment]
这个路径下本来就没东西，可以访问 http://ip:port/docs

**Comment by howardgriffin** [comment]
明白了，谢谢
