### ISSUE TITLE
新表情期望

### ISSUE THREAD

**Issue by MobiusT** [MeetWq/meme-generator#56]
![QQ图片20230921000733](https://github.com/MeetWq/meme-generator/assets/62053271/b0363acf-aee9-44d3-8419-839af18a3fa8)
![QQ图片20230921000820](https://github.com/MeetWq/meme-generator/assets/62053271/b331fca6-c746-480b-9a30-3b042b783b7a)

**Comment by MeetWq** [comment]
add in #120 #121
