### ISSUE TITLE
表情包制作返回的清单无法显示中文字符

### ISSUE THREAD

**Issue by exusiai07** [MeetWq/meme-generator#61]
在aws ec2 ubuntu上部署机器人以后，已按照提示安装字体。含中文字符的表情可以正常制作，但表情包制作指令返回的图片格式清单里，中文字符无法显示，请问需要加装什么字体？

![QQ图片20231004112521](https://github.com/MeetWq/meme-generator/assets/112692808/c30b2c3e-96b2-4b73-b7b3-02118fc7c092)

**Comment by jcjrobert** [comment]
#22

**Comment by exusiai07** [comment]
> #22

尝试过删缓存了，依然不行，这个问题只出现在表情包制作指令返回的这个清单图片里，其他带中文字符的表情没有这个问题。

**Comment by MeetWq** [comment]
https://github.com/noneplugin/nonebot-plugin-memes/issues/55

**Comment by exusiai07** [comment]
> [noneplugin/nonebot-plugin-memes#55](https://github.com/noneplugin/nonebot-plugin-memes/issues/55)

可以了，非常感谢
