### ISSUE TITLE
【报错】importError: DLL load failed while importing cv2:我不到指定的模块。

### ISSUE THREAD

**Issue by Agnes4m** [MeetWq/meme-generator#65]
安装方法：nb plugin install xxx
系统：win2012
![image](https://github.com/MeetWq/meme-generator/assets/70925546/8d8af01f-444b-482e-9467-19b91501b52c)

**Comment by MeetWq** [comment]
win server 需要安装桌面体验

**Comment by Avegardero** [comment]
我的win server 2022 带了桌面体验 也是这个报错

**Comment by lgc2333** [comment]
related with #66
