### ISSUE TITLE
ImportError: DLL load failed while importing _cext: 找不到指定的模块。

### ISSUE THREAD

**Issue by Avegardero** [MeetWq/meme-generator#66]
![{C941AAD0-AA8B-47ec-9921-DE2EDCD40DB5}](https://github.com/MeetWq/meme-generator/assets/76992712/dd241b71-7d17-4c1c-966d-935128d4431b)
![1699694388318](https://github.com/MeetWq/meme-generator/assets/76992712/7110d8e1-a9c1-4273-82d5-135bed53b0e5)

**Comment by lgc2333** [comment]
安装vc运行库
https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2015-2017-2019-and-2022
