### ISSUE TITLE
raise_sign中的fontname是否更改为FZShaoEr-M11S好一些

### ISSUE THREAD

**Issue by a563696823** [MeetWq/meme-generator#7]
https://github.com/MeetWq/meme-generator/blob/c9672464b34b4e49c4a8b7e897e8db02df385ecb/meme_generator/memes/raise_sign/__init__.py#L25

`FZSEJW.ttf`的fontname是`FZShaoEr-M11S`，现在使用`FZSEJW`可以读取到系统安装的字体，但是好像不能寻找到用fontmanager添加的字体

**Comment by MeetWq** [comment]
确实应该改一下

**Comment by MeetWq** [comment]
8865f14722fce19a269db75d15f50a0b95951206
