### ISSUE TITLE
可否加点新表情，希望能新增点梗

### ISSUE THREAD

**Issue by HMSXEF** [MeetWq/meme-generator#78]

**Comment by jcjrobert** [comment]
可以在issue里发你期望制作的表情，或者在群里交流

**Comment by HMSXEF** [comment]
> 可以在issue里发你期望制作的表情，或者在群里交流

稍等（）

**Comment by HMSXEF** [comment]
![Screenshot_20240107_110628_edit_304971310276370.jpg](https://github.com/MeetWq/meme-generator/assets/141598320/1a6dca64-407f-4381-9798-55660f2d4147)

![Screenshot_20240107_110826_edit_305182757854258.jpg](https://github.com/MeetWq/meme-generator/assets/141598320/fa24eced-ed64-42b3-a3ce-e9f1bb207a38)
![Screenshot_20240107_111634.jpg](https://github.com/MeetWq/meme-generator/assets/141598320/a1d65818-2f82-496e-8b27-cf73da29e723)


因为我有的表情都有字符，我也不知道怎么去（抱头痛哭）之后我把字去掉再发
emm最后能不能改头像，然后在框里添加字，😂😂😂然后这名字能改就改吧，没大问题

**Comment by HMSXEF** [comment]
![Screenshot_20240107_111753_edit_305552039350784.jpg](https://github.com/MeetWq/meme-generator/assets/141598320/f98b3f9b-eea2-45b3-820a-585878686b2c)

然后这个………EMM不行就说垮起个（）

**Comment by HMSXEF** [comment]
不太清楚这能不能审核过去（雷蒙多的看了属实想笑）

**Comment by dkqdb66** [comment]
> 可以在issue里发你期望制作的表情，或者在群里交流

有群吗，我有想法

**Comment by MeetWq** [comment]
> > 可以在issue里发你期望制作的表情，或者在群里交流
> 
> 有群吗，我有想法

主页标签里有写

**Comment by HMSXEF** [comment]
我才发现issue没关）
