### ISSUE TITLE
用pip安装完库，输入图片安装指令时弹出错误

### ISSUE THREAD

**Issue by guomangbigcute** [MeetWq/meme-generator#87]
meme : 无法将“meme”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径正确
，然后再试一次。
所在位置 行:1 字符: 1
+ meme download
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (meme:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by KomoriDev** [comment]
是在虚拟环境中安装的吗？如果是，应先进入虚拟环境后再使用 `meme` 命令
