### ISSUE TITLE
docker部署的字体不完整

### ISSUE THREAD

**Issue by LHXCxyw** [MeetWq/meme-generator#89]
docker部署的字体不完整，是需要设置什么吗，还是本来就缺少了字体
这是docker部署的
![4646d2b0e83b3e6bbf47335f430fa091](https://github.com/MeetWq/meme-generator/assets/98746227/83f39123-66d1-4d87-8832-4ff2e125bb1c)
这是演示里的
![image](https://github.com/MeetWq/meme-generator/assets/98746227/709b3234-0737-4916-9ad9-7a6dd6d3b979)
演示的字体更粗

**Comment by MeetWq** [comment]
确实有区别，我有空再来改（咕~）

**Comment by MeetWq** [comment]
我调整了一下，可以用最新的 docker 试试（`main` tag）
