### ISSUE TITLE
不知道是图片表情包对图片大小现在还是没有适配拉特兰客户端，上次图片一直错误

### ISSUE THREAD

**Issue by HL-Light** [MeetWq/meme-generator#94]
![image](https://github.com/MeetWq/meme-generator/assets/116658416/edd14714-bbe9-4d15-93ef-fdbbb5ab78a7)
![image](https://github.com/MeetWq/meme-generator/assets/116658416/d3f0adec-d379-4fb0-99d2-0fc90ff76aa1)

**Comment by MeetWq** [comment]
你的拉格兰是什么版本的？正常情况下接收到的图片应该有 url 字段，如
```
'[image:file=http://gchat.qpic.cn/gchatpic_new/1875806843/905796188-2509488978-5...,url=http://gchat.qpic.cn/gchatpic_new/1875806843/905796188-2509488978-5...]'
```

另外，这种问题应该在 `nonebot-plugin-memes` 下面问，这边先 close 了

以及，问问题麻烦说清楚点，把字打对。。。

**Comment by HL-Light** [comment]
orz，不好意思，我没注意
